name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHP ${{ matrix.php }}, ZTS=${{ matrix.zts }}
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        php:
          - 5.6.40
          - 7.0.33
          - 7.1.33
          - 7.2.34
          - 7.3.33
          - 7.4.29
          - 8.0.18
          - 8.1.5
        zts: [on, off]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/php
          key: php-build-${{ matrix.php }}-zts-${{ matrix.zts }}-minimal-

      - name: "Install cached PHP's dependencies"
        if: steps.php-build-cache.outputs.cache-hit == 'true'
        run: ${{ github.workspace }}/php/install-dependencies.sh

      - name: Clone php-build/php-build
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: php-build/php-build
          path: ${{ github.workspace }}/php-build

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          cd ${{ github.workspace }}/php-build
          ./install-dependencies.sh
          echo \
              --disable-all \
              --disable-debug \
              --enable-cli \
              --with-openssl \
              --with-zlib \
              --with-zlib-dir=/usr > ./share/php-build/default_configure_options
          PHP_BUILD_ZTS_ENABLE=${{ matrix.zts }} ./bin/php-build ${{ matrix.php }} ${{ github.workspace}}/php
          cp ./install-dependencies.sh ${{ github.workspace }}/php

      - name: Install extension
        run: |
          cd ${{ github.workspace }}
          ${{ github.workspace }}/php/bin/phpize
          ./configure --with-php-config=${{ github.workspace }}/php/bin/php-config
          make -j8 install
          echo "extension=crypto.so" > ${{ github.workspace }}/php/etc/conf.d/crypto.ini

      - name: Run PHPT tests
        run: |
          cd ${{ github.workspace }}
          REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS='--show-diff' make test
