name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHP ${{ matrix.php }}, ZTS=${{ matrix.zts }}
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        php:
          - 5.6.40
          - 7.0.33
          - 7.1.33
          - 7.2.34
          - 7.3.33
          - 7.4.29
          - 8.0.27
          - 8.1.26
          - 8.2.13
          - 8.3.0
        zts: [enable, disable]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Restore PHP build cache
        uses: actions/cache@v3
        id: php-build-cache
        with:
          path: ${{ github.workspace }}/php
          key: php-${{ matrix.php }}-zts-${{ matrix.zts }}

      - name: Install PHP build dependencies
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install \
            re2c

      - name: Get number of CPU cores
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Download PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: curl -L https://github.com/php/php-src/archive/refs/tags/php-${{ matrix.php }}.tar.gz | tar -xz

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        working-directory: php-src-php-${{ matrix.php }}
        run: |
          ./buildconf --force
          ./configure \
              --disable-all \
              --disable-debug \
              --enable-cli \
              --with-openssl \
              --with-zlib \
              --with-zlib-dir=/usr \
              --${{ matrix.zts }}-zts \
              --prefix="${{ github.workspace }}/php"
          make -j ${{ steps.cpu-cores.outputs.count }} install

      - name: Install extension
        run: |
          cd ${{ github.workspace }}
          ${{ github.workspace }}/php/bin/phpize
          ./configure --with-php-config=${{ github.workspace }}/php/bin/php-config
          make -j8 install

      - name: Run PHPT tests
        run: |
          cd ${{ github.workspace }}
          REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS='--show-diff' make test
